### ISSUE TITLE
Link does not seem to work well?

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#106]
https://fastly.picsum.photos/id/580/536/354.jpg?hmac=O7XZPRwRGaF4LAHHcZPi0QPNcDuJChYW0G_iu0pSfKg

Uploading this picture using the link method just doesn't seem to work. It just reloads the page after I click "Upload"

![image](https://github.com/uNotesOfficial/upup/assets/43147238/d884a5fb-b68f-4be2-94fe-14c3ad029e3c)

**Comment by MohamedBechirMejri** [comment]
@AminDhouib 

https://github.com/uNotesOfficial/upup/assets/76930306/ea8e7a8c-0c2b-4661-9245-b50b72c9cc45

It's working fine in upup so I think it's a unotes bug, I will check it out.

also, i think we should rename the upload button since it's not really uploading anything but rather getting the image from the link and adding it to the files list so maybe it should be called 'Get Image' or something similar

**Comment by AminDhouib** [comment]
Check it out and report back. 

Also agreed @MohamedBechirMejri

**Comment by MohamedBechirMejri** [comment]
The problem was the container element, it was a form so when we click on the upload button it thinks we're submitting doc. I switched it to a div element but i'll also edit all buttons in upup to not submit forms
